### ISSUE TITLE
Page.InsertText(): Cannot use standard fonts

### ISSUE THREAD

**Issue by OliverSteinau** [ArtifexSoftware/MuPDF.NET#101]
page.InsertText(new Point(100, 100), "text") will throw an exception saying that both fontname and fontfile must be specified

(version 2.0.10-alpha)

**Comment by greendreamer** [comment]
Thanks for your report, @OliverSteinau

MuPDF.NET doesn't support standard font and so users have to specify user's font file like *.ttf.

**Comment by green0317** [comment]
MuPDF.NET doesn't support built-in fonts anymore and you should specify custom font when necessary.
