### ISSUE TITLE
Page.InsertText() outputs wrongly formatted borderWidth ('w')

### ISSUE THREAD

**Issue by OliverSteinau** [ArtifexSoftware/MuPDF.NET#102]
If borderWidth is not specfied for Page.InsertText(...), the default value (0.05f) is output using just `text9 += $"{borderWidth} w ";`, which results in `0,05 w` (with a comma) being written out, instead of `0.05 w` (with a dot) if the current CultureInfo uses a comma for number formatting.

(version 2.0.10-alpha)

**Comment by greendreamer** [comment]
Thanks for your report, @OliverSteinau 

it will be fix in next version.
