### ISSUE TITLE
no visible output using Page.InsertText()

### ISSUE THREAD

**Issue by OliverSteinau** [ArtifexSoftware/MuPDF.NET#103]
Simple program
```
        Document doc = new();
        Page page = doc.NewPage();
        page.InsertText(new Point(100, 100), "text", fontName: "arial", fontFile: "c:/windows/fonts/arial.ttf");
        doc.Save("d:/test.pdf", pretty: 1);
```
produces no visible output.

(version 2.0.10-alpha)

**Comment by greendreamer** [comment]
that is working on my side. there seems to be wrong stuff on your one or let us discuss further.

Here is the correct output:
![image](https://github.com/ArtifexSoftware/MuPDF.NET/assets/146982441/ecf572da-04d9-4ae7-83f4-9a62a053c7ef)

**Comment by greendreamer** [comment]
Fixed with MuPDF.NET version 2.0.11-alpha
