### ISSUE TITLE
Save page to pixmap with defined dpi crops the page image

### ISSUE THREAD

**Issue by saper-2** [ArtifexSoftware/MuPDF.NET#108]
Hi,

Forwarding issue from discord...

Using latest MuPDF.NET from nuget.

When I export page to pixmap with specified dpi and save to file, the image being cropped (I think to the initial page size).

Here is code:
```cs
int dpi = 200;
Console.WriteLine("Saving pages to PNGs...");
for (int p = 0; p < doc.GetPageCount(); p++)
{
    string page_file = Path.Combine(Path.GetDirectoryName(pdf_file), Path.GetFileNameWithoutExtension(pdf_file) + "-" + p.ToString() + ".png");

    MuPDFPage page = doc.LoadPage(p);

    Pixmap pxm = page.GetPixmap(dpi: dpi);
    pxm.SetDpi(dpi, dpi); //
    Console.WriteLine(" - Page " + p.ToString() + " into: " + page_file);
    pxm.Save(page_file, "png");
}
```

And preview, left is without dpi (it's too small for me). And right is what I get when I set dpi:
![image](https://github.com/ArtifexSoftware/MuPDF.NET/assets/8533673/acd52ae6-3eb7-46fd-b34f-935071a1a549)

*FIY: there is no problem with PyMuPDF - just checked*

**Comment by greendreamer** [comment]
Fixed with MuPDF.NET v2.0.12
