### ISSUE TITLE
How to adapt to Linux platform

### ISSUE THREAD

**Issue by GithubXkw1573** [ArtifexSoftware/MuPDF.NET#112]
I want to use it for Linux platform, I noticed that dependent maui-tizen,  so I can‘t be used on Linux，
How to compile on linux and get dll

**Comment by greendreamer** [comment]
Hi @GithubXkw1573 , here is the way to get dll for linux.

## 1. Install .NET Environment (SDK, Runtime, ..)
- https://learn.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website

## 2. Install .NET Maui Environment

- https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?view=net-maui-8.0&tabs=visual-studio-code

## 3. Get C# binding for Linux with following guide.
- Clone mupdf from `https://github.com/ArtifexSoftware/mupdf`
- Build C# binding with `https://mupdf.readthedocs.io/en/latest/language-bindings.html?utm_source=mupdf&utm_medium=website&utm_content=cta-header-link#id1`
- Please find `mupdf.cs` and `mupdfcsharp.so` in `../mupdf/build/shared-release-x64-py3.12`

## 4. Build MuPDF.NET
- Clone this repo from `https://github.com/ArtifexSoftware/MuPDF.NET/`
- Replace C# binding in `MuPDF.NET/MuPDF.NET` to build on Linux.
Delete  `mupdf.cs`, `mupdfcpp64.dll`, `mupdfcsharp.dll` in folder `MuPDF.NET/MuPDF.NET`.
Copy `mupdf.cs`, `mupdfcsharp.so` from `mupdf/build/shared-release-x64-py3.12` to folder `MuPDF.NET/MuPDF.NET`.
- Build MuPDF.NET with `dotnet build --configuration Release MuPDF.NET.csproj`

Please find shared libraries in `MuPDF.NET/bin` and use that for your purpose.

You may need c# binding to run MuPDF.NET. Those are `libmupdf.so`, `libmupdf.so.25.0`, `libmupdfcpp.so`, `libmupdfcpp.so.25.0` in `../mupdf/build/shared-release-x64-py3.12`.

**Comment by GithubXkw1573** [comment]
I decided to use pdfsharpcore ultimately ,because I am in Avalonia not Maui, even though ,thank you for your guiding a lot!
