### ISSUE TITLE
Dotnet Standard support

### ISSUE THREAD

**Issue by jgunter7** [ArtifexSoftware/MuPDF.NET#119]
Hello MuPDF,

Are there plans to support the dotnet standard spec? https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

This would allow applications across various dotnet versions to be able to integrate with your nuget library.

.NET Framework 4.8.1 is still alive, and has no EOL date. Projects made with "dotnetstandard2.0" can support .NET 4.8.1 and the latest supported version of dotnet core as well (6, 7 & 8)

**Comment by greendreamer** [comment]
We will consider adding this kind of back-level support in due time. At the moment we still are busy integrating new features.

**Comment by CanadianHusky** [comment]
I agree. There are tons of existing of .Net Framework 4.8+ apps out there that will be maintained for years to come.
Not everyone switches to the latest .Net Core right away when the app has millions of lines of code.
Are there plans to support .Net Framework 4.8 , 4.8.1 over .Net Standard 2.0 ?
