### ISSUE TITLE
.Net8.0 & win11 runtime error!!!

### ISSUE THREAD

**Issue by heyhumor** [ArtifexSoftware/MuPDF.NET#121]
![image](https://github.com/user-attachments/assets/0745cd47-adbc-4bf4-b3d1-adfebf16f64f)
I am using **.NET 8.0 with VS2022**, and the program compiles and runs normally on **Windows 10 (version 10.0.19045.4780)**. 
However, it encounters an issue when running on **Windows 11 (version 11.0.22631.2681)**. 
The execution fails when trying to load with "Document doc = new Document(pdfPath);", and the exception message shows: "The type initializer for 'MuPDF.NET.Document' threw an exception." 
Could you please let me know if **Windows 11 is supported**? Is there a solution for this issue? Thank you!

**Comment by greendreamer** [comment]
Hi @heyhumor , MuPDF.NET supports Win11 and I have tested that works.

- MuPDF.NET version 2.1.0
- Windows 11 (version 11.0.22631.4037)
- VS 2022
- .NET 8.0

Please check again.

**Comment by heyhumor** [comment]
@greendreamer 
Thank you for your reply. I found the cause of the issue—it was due to the **virtual machine.** 
The error occurred on the **VM Ware** win11 virtual machine, but after installing it on a physical machine, it worked fine. 

What could be the differences in the virtual machine environment? Could it be due to the underlying libraries?
