### ISSUE TITLE
Recolor option 

### ISSUE THREAD

**Issue by maivana96** [ArtifexSoftware/MuPDF.NET#128]
Hi,

Is it possible to rewrite command - 'mutool recolor -o "{output}" -c cmyk "{input}"' by using MuPDF.NET?
I am trying to convert vector files to the CMYK pdf file.

Kind regards,
Ivana

**Comment by green0317** [comment]
Hi @maivana96 ,

that is impossible for now, but that may be implemented according to user's demand, I think.

**Comment by maivana96** [comment]
Hi @green0317 , one additional question, is it possible to convert SVG to PDF using MuPDF.NET package? I would like to achieve same results as **mutool convert -o "{output}" "{input}"** command when mutool is used if it is possible?

**Comment by maivana96** [comment]
I've posted this question in another issue, so this one I will close. Thank you for your answer.
