### ISSUE TITLE
Convert SVG file to PDF

### ISSUE THREAD

**Issue by maivana96** [ArtifexSoftware/MuPDF.NET#129]
Hi, is it possible to convert SVG to PDF using MuPDF.NET package? I would like to achieve same results as mutool convert -o "{output}" "{input}" command when mutool is used if it is possible?

**Comment by JorjMcKie** [comment]
To be confirmed by @green0317 but you should be able to open an SVG as a Document.
Then use [Convert2Pdf](https://mupdfnet.readthedocs.io/en/latest/api/document.html#Document.Convert2Pdf).

**Comment by jamie-lemon** [comment]
I've just checked with `mutool convert` and the linear gradient isn't supported for SVG files - same result. Unfortunately this would take a fair amount of work to implement. So basically it would seem that linear gradients are not supported in MuPDF.

**Comment by JorjMcKie** [comment]
@jamie-lemon as suspected

**Comment by maivana96** [comment]
Thank you on explanation. Good to know.
