### ISSUE TITLE
Recolor API output

### ISSUE THREAD

**Issue by maivana96** [ArtifexSoftware/MuPDF.NET#136]
Hi,

I want to use recolor API to convert the file to CMYK pdf, here is my code :

        private byte[] RecolorCommand(byte[] byteArray)
        {
            var muPDFDocument = new Document(stream: byteArray);
            muPDFDocument.Recolor(0,"CMYK");
            return [.. muPDFDocument.Stream];
        }

I am wondering is this approach good, since I am not sure will result of the recolor API will update stream inside the Document file.

Kind regards,
Ivana

**Comment by green0317** [comment]
Hi @maivana96 , currently that doesn't work, will fix that soon.

**Comment by green0317** [comment]
Hi @maivana96 , I think Stream doesn't need anymore in Document. Please use `Write` method.

**Comment by maivana96** [comment]
Hi @green0317  , So the recolor API is working fine or I should wait for fix,  just need to use Write method to save the converted file?

**Comment by green0317** [comment]
Recolor API is workign fine for now.

**Comment by maivana96** [comment]
It is working now as I expected.  :) Thank you very much on really quick answer.
