### ISSUE TITLE
Page.DeleteImage function Error

### ISSUE THREAD

**Issue by Samtech100** [ArtifexSoftware/MuPDF.NET#139]
Source code:
public void DeleteImage(int xref)
        {
            Pixmap pix = new Pixmap(new ColorSpace(Utils.CS_GRAY), new IRect(0, 0, 1, 1), 1);
            pix.ClearWith();
            ReplaceImage(xref, pixmap: pix);
        }
Result:
Use Page in the program After the DeleteImage function, use document The GetPageImages function obtains a List<Entry>list containing 2 objects, which does not delete the images within the original page, but instead uses a new image to overwrite the original image, which is different from the literal meaning of DeleteImage.

**Comment by JorjMcKie** [comment]
This function works as intended: It achieves a result **_as if_** the image were deleted.
Using the right save options will remove the image from the file.
