### ISSUE TITLE
Prevent dll download

### ISSUE THREAD

**Issue by maivana96** [ArtifexSoftware/MuPDF.NET#146]
Hi,

I've imported MuPDF.NET library as dependency in my .net 8 core project as NuGet package. I've noticed that after running some commands from package, these two DLLs (mupdfcsharp.dll and mupdfcpp64.dll) are downloaded in the project root folder, is there any way to prevent these download action or include it directly into bin folder?

**Comment by jamie-lemon** [comment]
For me these two DLLs only exist when I run a project and so are found in `bin/Debug/net8.0` I'm confused why you would see them in the top level - is this next to your main `.sln` file?

**Comment by maivana96** [comment]
![image](https://github.com/user-attachments/assets/b83ce459-6294-4ff5-93dc-d70729e73d0d)

Here is a screenshot of the project setup. 

There is one class library project that has installed MuPDF.NET NuGet package and includes usage of recolor and convert methods from MuPDF.NET library. This project is added as dependency project in the API .NET Core 8 project. 

I've noticed that after triggering the endpoint that executes the commands from MuPDF.NET library, the DLL files are downloaded in the root of API project, even though this project does not have directly dependency to MuPDF.NET only includes dependency to class library project and DLLs are also downloaded to bin/Debug/net8.0 folder.

So there is no error, code is working fine, I am just wondering why these DLL files are downloaded like that and is it possible to prevent it?

**Comment by MaksymTkachuk** [comment]
@jamie-lemon @maivana96 
I checked the issue at my local.
https://github.com/ArtifexSoftware/MuPDF.NET/issues/146
mupdfcpp64.dll and mupdfcsharp.dll files are created in "Working Directory" of the executable.
When the .exe file is executed, those are created in the same directory where the .exe file exists.
If run the project directly in Visual Studio, "Working Directory" is the Project's root directory by default.
Therefore, mupdfcpp64.dll and mupdfcsharp.dll files are created in the Project's root directory as in the issue.
To avoid this, need to change the Project's working directory.
For example, in Project property window.
![image](https://github.com/user-attachments/assets/669018c0-6ba1-44be-b218-ed31eec188c5)

@maivana96 
This is just my opinion. 
I don't know the specifics of your project.
(If possible, I would like to confirm it directly in your project, but I think it would be your private project.)
So, please check it at your project.
Thanks.
