### ISSUE TITLE
TextWriter.FillTextbox() will always throw exception

### ISSUE THREAD

**Issue by OliverSteinau** [ArtifexSoftware/MuPDF.NET#99]
TextWriter.FillTextbox() has a check "if (rect.IncludePoint(pos) != rect)" which will always be true, because rect.IncludePoint() will always return a new Rect object, and hence this condition will always be true, causing Exception "Text must start in rectangle" to always be thrown.
A simple "point_in_rect" test is probably preferrable.
(in 2.0.10-alpha)

**Comment by greendreamer** [comment]
Fixed with MuPDF.NET version 2.0.11-alpha
